System Modules/Admin/Areas/Admin/Controllers/SystemValuesController.cs
using System;
using System.Web.Mvc;
using CloudCore.Admin.Models;
using CloudCore.Web.Core.BaseControllers;


namespace CloudCore.Admin.Controllers
{
    public class SystemValuesController : InternalAuthenticatedController
    {
        public ActionResult Create()
        {
            var model = new SystemValueCategoryCreateModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(SystemValueCategoryCreateModel model)
        {
            model.CreateCategory();
            return RedirectToAction("Details", new { CategoryId = model.CategoryId });
        }

        public ActionResult Search()
        {
            var model = new SystemValueCategorySearchModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Search(SystemValueCategorySearchModel model)
        {
            model.Search();
            return View(model);
        }


        public ActionResult Details(int categoryId)
        {
            var model = new SystemValueCategoryDetailsModel();
            model.CategoryId = categoryId;
            model.GetSystemValues();
            return View(model);
        }

        public ActionResult AddSystemValue(int CategoryId)
        {
            var model = new SystemValueCreateModel();
            model.CategoryId = CategoryId;
            return View(model);
        }

        [HttpPost]
        public ActionResult AddSystemValue(SystemValueCreateModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    model.AddSystemValue();
                    ShowSuccessMessage("System Value sucessfully added.");
                    return RedirectToAction("Details", new { CategoryId = model.CategoryId });
                }
                catch (Exception ex)
                {
                    ShowErrorMessage(ex.Message);
                }
            }
            return View(model);
        }

        public ActionResult ModifySystemValue(int ValueId)
        {
            var model = new SystemValueUpdateModel();
            model.ValueId = ValueId;
            return View(model);
        }

        [HttpPost]
        public ActionResult ModifySystemValue(SystemValueUpdateModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    model.Update();
                    ShowSuccessMessage("System Value sucessfully updated.");
                    return RedirectToAction("Details", new { CategoryId = model.SystemValue.CategoryId });
                }
                catch (Exception ex)
                {
                    ShowErrorMessage(ex.Message);
                }
            }
            return View(model);
        }

    }
}

System Modules/Admin/Areas/Admin/Views/SystemValues/AddSystemValue.cshtml
@inherits CloudCore.Web.Core.BaseViews.WebView<CloudCore.Admin.Models.SystemValueCreateModel>
@{
    ViewBag.Title = "Add System Value";
}

@using (Html.BeginForm())
{
    
    using (FormLayout.BeginTable())
    {
        @FormLayout.AddTitleHeaderRow("System Value Details")
        @FormLayout.AddTextboxRowFor(model => model.ValueName)
        @FormLayout.AddTextboxRowFor(model => model.ValueData)
        @FormLayout.AddTextAreaFor(model => model.ValueDescription,5,30)
    }
    FormLayout.AddSubmitButtonWithBar("Save");
   

}

System Modules/Admin/Areas/Admin/Views/SystemValues/Create.cshtml
@inherits CloudCore.Web.Core.BaseViews.WebView<CloudCore.Admin.Models.SystemValueCategoryCreateModel>
@{
    ViewBag.Title = "Add System Value Category";
}

@using (Html.BeginForm())
{
    
    using (FormLayout.BeginTable())
    {
        @FormLayout.AddTitleHeaderRow("System Value Category Details")
        @FormLayout.AddTextboxRowFor(model => model.CategoryName)
    }
    FormLayout.AddSubmitButtonWithBar("Save");    
}

System Modules/Admin/Areas/Admin/Views/SystemValues/Details.cshtml
@inherits CloudCore.Web.Core.BaseViews.WebView<CloudCore.Admin.Models.SystemValueCategoryDetailsModel>
@{
    ViewBag.Title = "System Value Category Details";
}



@using (Html.BeginForm())
{ 
    
    @(Html.InfoGrid(Model.CategorySystemValues.AsQueryable())
    .Columns(column => 
        {
            column.For(result => Html.ActionLink(result.ValueName, "ModifySystemValue", new { valueId = result.ValueId })).Named("Value Name").SortColumnName("ValueName");
            column.For(result => result.ValueData);
            column.For(result => result.ValueDescription);
        })
        .Title("System Values")
    )
    FormLayout.AddRedirectButtonWithBar("Add System Value", Url.Action("AddSystemValue", "SystemValues", new { CategoryId = Model.CategoryId }));
    
    @*using (FormLayout.BeginTable())
    {
        @FormLayout.AddRedirectButtonRow("Add System Value", Url.Action("AddSystemValue", "SystemValues", new { CategoryId = Model.CategoryId }), CloudCore.Core.Helpers.FormLayout.TDFillerPosition.None)
    }*@
}      

System Modules/Admin/Areas/Admin/Views/SystemValues/ModifySystemValue.cshtml
@inherits CloudCore.Web.Core.BaseViews.WebView<CloudCore.Admin.Models.SystemValueUpdateModel>
@{
    ViewBag.Title = "Update System Value";
}

@using (Html.BeginForm())
{
    
    using (FormLayout.BeginTable())
    {

        @FormLayout.AddTitleHeaderRow("System Value Details")
        @FormLayout.AddTextboxRowFor(model => model.ValueName,new {@readonly = true})
        @FormLayout.AddTextboxRowFor(model => model.ValueData)
        @FormLayout.AddTextAreaFor(model => model.ValueDescription,5,70)
    }
    FormLayout.AddSubmitButtonWithBar("Update System Value");
}

System Modules/Admin/Areas/Admin/Views/SystemValues/Search.cshtml
@inherits CloudCore.Web.Core.BaseViews.WebView<CloudCore.Admin.Models.SystemValueCategorySearchModel>
@{
    ViewBag.Title = "Search System Value Category";
}


@using (Html.BeginForm())
{ 
    using(FormLayout.BeginTable())
    {
        @FormLayout.AddFilterEditRowFor(m => m.CategoryName, m => m.FilterOptions);
    }
    FormLayout.AddSubmitButtonWithBar("Search");    
    @(Html.SearchGrid(Model.SearchResults.AsQueryable())
    .Columns(column => 
        {
            column.For(r => Html.ActionLink(r.CategoryName, "Details", new { categoryId = r.CategoryId})).Named("Category Name");
        })
            .Title("Access Pool Search Results")
    )
}      