System Modules/CUI/Areas/CUI/Controllers/CUIPopupController.cs
using System;
using System.Data.SqlClient;
using System.IO;
using System.Web.Mvc;
using System.Linq;
using CloudCore.Domain;
using CloudCore.Web.Areas.CUI.Helpers;
using CloudCore.Web.Models;
using CloudCore.Web.Core.BaseControllers;
using CloudCore.Web.Core.Caching;
using CloudCore.Web.Core.Security.Authentication;

using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
using CloudCore.Data;

namespace CloudCore.Web.Controllers
{
    public partial class CUIPopupController : AuthenticatedPopupController
    {
        public ActionResult AddDashboard(int tilePosition)
        {
            var model = new AvailableUsersDashboardItemsModel
            {
                TilePosition = tilePosition
            };

            model.PopulateUserAvailableDashboardItems( CloudCoreIdentity.UserId);

            return View(model);
        }

        [HttpPost]
        public ActionResult AddDashboard(AvailableUsersDashboardItemsModel model)
        {
            model.DashboardAddToCurrentUser();

            return ClosePopUpResult();
        }

        public ActionResult UserNotification(int notificationId)
        {
            var userId = CloudCoreIdentity.UserId;

            var model = new UserNotificationModel();
            model.LoadUserNotificationAndMarkAsRead(userId, notificationId);

            SessionInfo.HasNotifications = CloudCoreDB.Context.Cloudcore_VwUserNotification.Where(un => un.UserId == userId && un.HasRead == false).Any();

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult UserNotification(UserNotificationModel model)
        {
            CloudCoreDB.Context.Cloudcore_NotificationRemove((int)model.NotificationId, CloudCoreIdentity.UserId);
            ShowSuccessMessage("Notification successfully removed");
            return RedirectToAction("Notifications", "Tools", new { area = "CUI" });
        }

        public ActionResult CloseNotification(UserNotificationModel model)
        {
            return ClosePopUpResult();
        }

        public ActionResult SearchFavourite()
        {
            return View(new AddFavouritesSearchModel());
        }

        [HttpPost]
        public ActionResult SearchFavourite(AddFavouritesSearchModel model)
        {
            model.Search();
            return View(model);
        }

        public ActionResult AddFavourite(Guid Reference)
        {
            try
            {
                UserProfile.AddFavourite( Reference, FavouriteType.Menu);
                ShowSuccessMessage("Favourite Added Successfully");
            }
            catch (SqlException ex)
            {
                if (ex.Message.Contains("7 menu item favourites"))
                {
                    ShowErrorMessage(ex.Message);
                }
            }

            return ClosePopUpResult();
        }

        public ActionResult ViewDashboard(int tilePosition)
        {
            var userId = CloudCoreIdentity.UserId;
            var dashboardTasks = new DashboardHelper();

            var userDashboardData = dashboardTasks.GetUserDashboardTileData(userId, tilePosition);

            var model = new ViewDashboardModel();

            if (userDashboardData != null)
            {
                model.TilePosition = tilePosition;
                model.UserId = CloudCoreIdentity.UserId;
                model.TileContextDefined = true;
                model.TileContext = userDashboardData.ResultData;
            }
            else
            {
                model.TilePosition = tilePosition;
                model.UserId = CloudCoreIdentity.UserId;
            }

            return View(model);
        }
    }
}

System Modules/CUI/Areas/CUI/Views/CUIPopup/AccessPoolLookup.cshtml
@using CloudCore.Core.Domain
@inherits CloudCore.Web.Core.BaseViews.LookupView<CloudCore.Web.Models.AccessPoolLookupModel>

@using (FormLayout.BeginModal("Search for Access Pool"))
{
    using (Html.BeginForm())
    {
        @Html.HiddenFor(m => m.LookupInputId)
        @Html.HiddenFor(m => m.LookupInputIdValue)
        
        using (FormLayout.BeginTable(FormLayoutType.Popup))
        {
            @FormLayout.AddFilterEditRowFor(m => m.Name, m => m.NameFilter)
            @FormLayout.AddFilterEditRowFor(m => m.ManagerName, m => m.ManagerNameFilter)
        }

        @(Html.SearchGrid(Model.SearchResults)
              .Columns(column =>
              {
//                  column.For(item => AddHrefToSetLookupValue("AccessPoolId", item.AccessPoolId.ToString(), "AccessPoolName", item.AccessPoolName, item.AccessPoolName)).Named("Access Pool Name");
                  column.For(item => AddHrefToSetLookupValue(Model, m => m.LookupInputId, m => m.LookupInputIdValue, item.AccessPoolId.ToString(), item.AccessPoolName, item.AccessPoolName)).Named("Access Pool Name");
                  column.For(r => r.ManagerName);
              })
              .Title("Access Pool Search Results")
        )

        @FormLayout.AddModalSearchButtonBar(Url.Action("AccessPoolLookup", "CUIPopup", new { area = "CUI" }))
    }
}

System Modules/CUI/Areas/CUI/Views/CUIPopup/AddDashboard.cshtml
@inherits CloudCore.Web.Core.BaseViews.PopupView<CloudCore.Web.Models.AvailableUsersDashboardItemsModel>
@{
    ViewBag.Title = "Select Dashboard Item";
}

@using (Html.BeginForm())
{
    @Html.HiddenFor(m => m.DashboardId)
    @Html.HiddenFor(m => m.TilePosition)
    @(Html.InfoGrid(Model.UserAvailableDashboardItems)
        .Title("")
            .EmptyTableItemName("No Available Dashboard Items Found")
        .PageSize(20)
        .Sort(null)
        .Columns(column =>
        {
            column.For(r => Html.Raw(string.Format(@"<a class=""addItem"" data-val-dashboardId=""{1}"" style=""cursor:pointer;"">{0}</a>", r.Title, r.Id)));
            column.For(r => r.Description);
        })
    )
}

<script type="text/javascript">
    $(document).ready(function () {
        $('.addItem').on('click', function () {
            $('#DashboardId').val($(this).attr('data-val-dashboardId'));
            
            $('form').submit();
        });
    });
</script>

System Modules/CUI/Areas/CUI/Views/CUIPopup/SearchFavourite.cshtml
@inherits CloudCore.Web.Core.BaseViews.PopupView<CloudCore.Web.Models.AddFavouritesSearchModel>
@{
    ViewBag.Title = "Select Menu Item Favourite";
}              

@using (Html.BeginForm())
{ 
    using(FormLayout.BeginTable())
    {
        @FormLayout.AddTextboxRowFor(m => m.Title);
    }
    FormLayout.AddSubmitButtonWithBar("Search");
    @(Html.SearchGrid(Model.SearchResults)
    .Columns(column => 
        {
            column.For(item => Html.ActionLink(item.Title, "AddFavourite", "CUIPopUp", new { Reference = item.Reference }, null)).Named("Menu Item");
        }).Title("Menu Item Search Results")
    )
}      

System Modules/CUI/Areas/CUI/Views/CUIPopup/UserLookup.cshtml
@using CloudCore.Core.Domain
@inherits CloudCore.Web.Core.BaseViews.LookupView<CloudCore.Web.Models.UserLookupModel>
@{
    ViewBag.Title = "Search for User";
}

@using (FormLayout.BeginModal("Find User"))
{
    using (Html.BeginForm())    
    {
        @Html.HiddenFor(m => m.LookupInputId)
        @Html.HiddenFor(m => m.LookupInputIdValue)
        
        using (FormLayout.BeginTable(FormLayoutType.Popup))
        {
            @FormLayout.AddFilterEditRowFor(m => m.UserFullName, m => m.UserFullNameOptions)
        }

        @(Html.SearchGrid(Model.SearchResults.AsQueryable())
           .Columns(column =>
           {
               column.For(item => AddHrefToSetLookupValue(Model, m => m.LookupInputId, m => m.LookupInputIdValue, item.UserId.ToString(), item.UserFullName, item.UserFullName)).Named("Name");
               //            column.For(item => SetLookUpControlValuesAsHref(item.UserId.ToString(), item.UserFullName, item.UserFullName)).Named("Name");
           })
           .Title("User Search Results")
        )
        @FormLayout.AddModalSearchButtonBar(Url.Action("UserLookup", "CUIPopup", new { area = "CUI" }))
    }
}    

System Modules/CUI/Areas/CUI/Views/CUIPopup/UserNotification.cshtml
@using CloudCore.Core.Domain
@inherits PopupView<UserNotificationModel>

@using (FormLayout.BeginModal("User Notification"))
{
    using (Html.BeginForm())
    {
        using (FormLayout.BeginTable(FormLayoutType.Popup))
        {
            @FormLayout.AddDisplayRowFor(m => m.Created)
            @FormLayout.AddDisplayRowFor(m => m.Subject)
            @Html.Raw(Model.MessageWithLinks)
        }
        
        FormLayout.AddModalSubmitButton("DELETE");
    }
}

System Modules/CUI/Areas/CUI/Views/CUIPopup/ViewDashboard.cshtml
@using System.Web.Optimization
@inherits CloudCore.Web.Core.BaseViews.PopupView<CloudCore.Web.Models.ViewDashboardModel>

@Scripts.Render("~/bundles/highcharts")

<div id="container" style="width:100%;height:100%;"></div>

<script type="text/javascript">
    var viewDashboard = function () {
        var self = this;

        function getDashboardOptions() {
            var item = parent.dashboardCache.getItem('@(Model.UserId + "_" + Model.TilePosition)');
            if (item == null)
                return null;
            return item.HighChartsOptions;
        }

        self.renderHighCarts = function () {
            
            @if (Model.TileContextDefined)
            {
                @:var options = { @Html.Raw(Model.TileContext) };
            }
            else
            {
                @:var options = JSON.parse(getDashboardOptions());
            }
            
            if (options != null) {
                if (options.chart == undefined) {
                    options.chart = {
                        options3d: { enabled: false }
                    };
                } else {
                    options.chart.options3d = { enabled: false }
                }

                $('#container').highcharts(options);
            } else {
                $('#container').html('<div style="text-align:center;vertical-align:middle;line-height:100%;">No chart data available</div>');
            }
        }

        return self;
    }();

    viewDashboard.renderHighCarts();

</script>